title: Blog cctpidmdlcdtc
description: Cómo construir tu propio imperio del mal desde la comodidad de tu casa
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
